services:
  vpn_server:
    build: .
    env_file:
      - .env
    volumes:
      - .:/app
    container_name: vpn_service
    ports:
      - "80:80"
      - "5000:5000"
    cap_add:
      - NET_ADMIN  # Required for networking commands in VPN setup
    restart: unless-stopped
